export const CHANGE_NUMBER = 'CHANGE_NUMBER';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_DONATIONS = 'FETCH_DONATIONS';
export const FETCH_DONATIONS_SUCCESS = 'FETCH_DONATIONS_SUCCESS';
export const FETCH_DONATIONS_FAIL = 'FETCH_DONATIONS_FAIL';

export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';

export const CREATE_USER ='CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
