export const CHANGE_NUMBER = 'CHANGE_NUMBER';

export const CHANGE_NAME = 'CHANGE_NAME';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_DONATIONS = 'FETCH_DONATIONS';
export const FETCH_DONATIONS_SUCCESS = 'FETCH_DONATIONS_SUCCESS';
export const FETCH_DONATIONS_FAIL = 'FETCH_DONATIONS_FAIL';

export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';

export const CREATE_USER ='CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const UPDATE_USER ='UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const CREATE_DONATION ='CREATE_DONATION'
export const CREATE_DONATION_SUCCESS = 'CREATE_DONATION_SUCCESS'
export const CREATE_DONATION_FAIL = 'CREATE_DONATION_FAIL'

export const ADD_TYPE ='ADD_TYPE'

export const REMOVE_TYPE ='REMOVE_TYPE'

export const CHANGE_RECEIVE_METHOD_ONLY ='RECEIVE_METHOD_ONLY'

export const CHANGE_RECEIVE_METHOD ='RECEIVE_METHOD'
export const CHANGE_RECEIVE_METHOD_SUCCESS ='RECEIVE_METHOD_SUCCESS'
export const CHANGE_RECEIVE_METHOD_FAIL ='RECEIVE_METHOD_FAIL'

export const SET_DEVICE_TOKEN ='SET_DEVICE_TOKEN'



